### ISSUE TITLE
Problem in installing hightail

### ISSUE THREAD

**Issue by hrushikesht** [dj3500/hightail#100]
I am using an Ubuntu 14.04 system.
My java verion is `1.7.0_121`. I run the executable using `java -jar Hightail-v0.9.6.jar`.
I got the following error:
`Exception in thread "main" java.lang.UnsupportedClassVersionError: org/hightail/ui/MainJFrame : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)`

**Comment by dj3500** [comment]
Not sure what that is, but have you tried updating your Java (to 1.8)?

**Comment by hrushikesht** [comment]
The issue was resolved by updating java to 8.
